# Generated by Django 3.1.6 on 2021-02-15 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cameraman',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='摄影师ID')),
                ('name', models.TextField(default='Null', max_length=40, verbose_name='名字')),
                ('description', models.TextField(default='无', max_length=400, verbose_name='介绍')),
                ('mark', models.TextField(default='默认标注', max_length=400, verbose_name='标注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='风格ID')),
                ('name', models.TextField(default='默认风格', max_length=40, verbose_name='风格')),
                ('mark', models.TextField(default='默认标注', max_length=400, verbose_name='标注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '风格信息表',
                'verbose_name_plural': '风格信息表',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='日志id')),
                ('title', models.CharField(default='默认标题', max_length=100, verbose_name='标题')),
                ('imgLevel1', models.ImageField(help_text='最大尺寸', upload_to='', verbose_name='图片')),
                ('imgLevel2', models.ImageField(help_text='第二大尺寸', upload_to='', verbose_name='图片')),
                ('imgLevel3', models.ImageField(help_text='第三大尺寸', upload_to='', verbose_name='图片')),
                ('content', models.CharField(default='默认日志内容', max_length=1000, verbose_name='日志内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('cameraman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoWeb.cameraman')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoWeb.category')),
            ],
            options={
                'verbose_name': '日志信息表',
                'verbose_name_plural': '日志信息表',
            },
        ),
    ]
