# Generated by Django 3.1.6 on 2021-02-15 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cameraman',
            options={'verbose_name': '摄影师信息表', 'verbose_name_plural': '摄影师信息表'},
        ),
    ]
