# Generated by Django 3.1.6 on 2021-02-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoWeb', '0003_auto_20210215_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(default='无', max_length=400, verbose_name='简介'),
        ),
    ]
