# Generated by Django 3.1.6 on 2021-02-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoWeb', '0006_auto_20210222_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='反馈id')),
                ('email', models.EmailField(help_text='O.O', max_length=254, verbose_name='邮箱地址')),
                ('message', models.TextField(help_text='长度不确定，暂时设为最长2000', max_length=2000, verbose_name='反馈内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '反馈信息表',
                'verbose_name_plural': '反馈信息表',
                'ordering': ['-created_at'],
            },
        ),
    ]
