# Generated by Django 3.1.6 on 2021-02-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoWeb', '0007_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.TextField(default='None', help_text='用户填的名字', max_length=100, verbose_name='名字'),
        ),
    ]
